services:
  unit:
    build:
      context: .
    volumes:
      - ./:/app

  redis:
    image: docker.io/bitnami/redis:6.2.6
    hostname: redis-rpa
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: percona:ps-5.7
    hostname: rpa-db
    platform: linux/amd64
    working_dir: /data/www
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=rpa
      - MYSQL_DATABASE=rpa
      - MYSQL_USER=rpa
      - MYSQL_PASSWORD=rpa
    volumes:
      - ./:/app
      - ./database/mysql.cnf:/etc/my.cnf.d/mysql-rpa.cnf
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
